services:
  mongo:
    image: mongo:7
    container_name: healthguard-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - healthguard_mongo_data:/data/db

volumes:
  healthguard_mongo_data:
